apiVersion: apps/v1
kind: Deployment 
metadata:
  name: go-app-deploymet
  namespace: go-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: ghcr.io/go-gke-images/go-app:latest
        resources:
          limits:
            memory: "8192Mi"
            cpu: "4"
          requests:
            memory: "256Mi"
            cpu: "250m"
