apiVersion: apps/v1
kind: Namespace
metadata:
  name: go-app
  namespace: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: ghcr.io/go-gke-images/go-app:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "4096Mi"
            cpu: "2"
          requests:
            memory: "256Mi"
            cpu: "250m"
