apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: go-app-ns
spec:
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer